In [87]:
import pandas as pd
import warnings
import numpy as np
import re
warnings.filterwarnings('ignore')

In [88]:
df =pd.read_csv('train.csv')
df = df[~df['근로기간'].isin(['Unknown'])]
print(df.head(1))
new_columns = {"대출금액": "loan_amount",'대출기간':'loan_period','근로기간':'working_year','주택소유상태':'property','연간소득':'incomeyear','부채_대비_소득_비율':'DTI','대출목적':'purpose_loan','최근_2년간_연체_횟수':'overdue_num','총상환원금':'total_repayment','총상환이자':'total_interest','총연체금액':'overdue_amount','대출등급':'Rank'}
df.rename(columns = new_columns,inplace=True)
df=df.drop(columns=['총계좌수','연체계좌수'])
df=df.drop(columns=['ID'])
df['property'] = df['property'].apply(lambda t: {np.nan:-1, 'RENT':1, 'MORTGAGE':2, 'OWN':3, 'ANY':4}[t]).astype(np.int8)
#df['loan_period'] = df['loan_period'].apply(lambda x: re.sub(r'\D', '', x))
#df['working_year'] = df['working_year'].apply(lambda x: re.sub(r'\D', '', x))
#r'\D' 숫자가 아닌 모든 문자
#df['working_year_numeric'] = df['working_year'].str.extract('(\d+)')
df['purpose_loan'] = df['purpose_loan'].apply(lambda t: {np.nan:-1,
                                                        '부채 통합':1,
                                                        '주택 개선':2,
                                                        '주요 구매':3,
                                                        '휴가':4,
                                                        '의료':5,
                                                        '자동차':'6',
                                                        '신용 카드':7,
                                                        '소규모 사업':'8',
                                                        '기타':'9',
                                                        '이사':'10',
                                                        '주택':'11',
                                                         '재생 에너지':'12'}[t]).astype(np.int8)

            ID      대출금액        대출기간     근로기간 주택소유상태      연간소득  부채_대비_소득_비율  \
0  TRAIN_00000  12480000   36 months  6 years   RENT  72000000         18.9

   총계좌수   대출목적  최근_2년간_연체_횟수  총상환원금  총상환이자  총연체금액  연체계좌수 대출등급
0    15  부채 통합             0      0    0.0    0.0    0.0    C

In [89]:
df['Rank'].unique()

array(['C', 'B', 'A', 'D', 'F', 'G', 'E'], dtype=object)

from torch.utils.data import Dataset

In [90]:
new_columns = {"대출금액": "loan_amount",'대출기간':'loan_period','근로기간':'working_year','주택소유상태':'property','연간소득':'incomeyear','부채_대비_소득_비율':'DTI','대출목적':'purpose_loan','최근_2년간_연체_횟수':'overdue_num','총상환원금':'total_repayment','총상환이자':'total_interest','총연체금액':'overdue_amount','대출등급':'Rank'}

In [91]:
#one_hot_encoding
#df = pd.get_dummies(df,columns=['...'])
df

,loan_amount,loan_period,working_year,property,incomeyear,DTI,purpose_loan,overdue_num,total_repayment,total_interest,overdue_amount,Rank
0,12480000,36 months,6 years,1,72000000,18.90,1,0,0,0.0,0.0,C
1,14400000,60 months,10+ years,2,130800000,22.33,2,0,373572,234060.0,0.0,B
2,12000000,36 months,5 years,2,96000000,8.60,1,0,928644,151944.0,0.0,A
3,14400000,36 months,8 years,2,132000000,15.09,1,0,325824,153108.0,0.0,C
5,4800000,36 months,10+ years,1,84000000,13.78,4,0,240216,55428.0,0.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...
96289,14400000,36 months,10+ years,2,210000000,9.33,7,0,974580,492168.0,0.0,C
96290,28800000,60 months,10+ years,2,132000000,5.16,2,0,583728,855084.0,0.0,E
96291,14400000,36 months,1 year,2,84000000,11.24,7,0,1489128,241236.0,0.0,A
96292,15600000,36 months,5 years,2,66330000,17.30,1,2,1378368,818076.0,0.0,D
96293,8640000,36 months,10+ years,1,50400000,11.80,7,0,596148,274956.0,0.0,C

In [92]:
from sklearn.preprocessing import LabelEncoder

# 가상의 데이터 생성
# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

# 라벨 인코딩 수행
df['Rank'] = label_encoder.fit_transform(df['Rank'])
df['loan_period'] = label_encoder.fit_transform(df['loan_period'])
df['working_year'] = label_encoder.fit_transform(df['working_year'])

In [93]:
df

,loan_amount,loan_period,working_year,property,incomeyear,DTI,purpose_loan,overdue_num,total_repayment,total_interest,overdue_amount,Rank
0,12480000,0,9,1,72000000,18.90,1,0,0,0.0,0.0,2
1,14400000,1,2,2,130800000,22.33,2,0,373572,234060.0,0.0,1
2,12000000,0,8,2,96000000,8.60,1,0,928644,151944.0,0.0,0
3,14400000,0,11,2,132000000,15.09,1,0,325824,153108.0,0.0,2
5,4800000,0,2,1,84000000,13.78,4,0,240216,55428.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
96289,14400000,0,2,2,210000000,9.33,7,0,974580,492168.0,0.0,2
96290,28800000,1,2,2,132000000,5.16,2,0,583728,855084.0,0.0,4
96291,14400000,0,0,2,84000000,11.24,7,0,1489128,241236.0,0.0,0
96292,15600000,0,8,2,66330000,17.30,1,2,1378368,818076.0,0.0,3
96293,8640000,0,2,1,50400000,11.80,7,0,596148,274956.0,0.0,2

In [94]:
X = df.drop(columns = ['Rank'])
y = df.Rank

In [96]:
#df['loan_period'] = pd.to_numeric(df['loan_period'])
#df['working_year'] = pd.to_numeric(df['working_year'])
#df['loan_period'] = df['loan_period'].astype(float)
#df['working_year'] = df['working_year'].astype(float)
#df['working_year'].unique()

array([ 9,  2,  8, 11, 12,  4,  0,  6, 10,  7, 13,  3, 14,  5,  1])

In [98]:
from sklearn.model_selection import train_test_split, GridSearchCV, \
RandomizedSearchCV, cross_val_score, RepeatedStratifiedKFold
X_train, X_test, y_train, y_test = \
train_test_split(X, y, random_state=0, test_size=0.2)

In [99]:
X_train

,loan_amount,loan_period,working_year,property,incomeyear,DTI,purpose_loan,overdue_num,total_repayment,total_interest,overdue_amount
48041,12000000,0,2,1,96000000,13.75,9,0,1240944,197484.0,0.0
8697,19440000,1,10,2,54000000,24.03,1,0,385392,708204.0,0.0
41428,30000000,1,2,1,84000000,9.24,1,1,715644,622140.0,0.0
93162,42000000,1,2,3,96000000,19.19,11,0,1729980,2533716.0,0.0
59109,15960000,1,2,2,96000000,25.40,2,1,375792,349368.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
22606,24000000,0,2,2,168000000,16.42,1,0,1153788,368172.0,0.0
48808,18000000,1,7,2,84000000,16.36,1,6,676032,489336.0,0.0
45320,42000000,1,2,3,122400000,36.48,1,1,874800,906444.0,0.0
46336,16560000,0,8,2,72000000,16.42,1,0,387456,132132.0,0.0
72612,4320000,0,8,1,68400000,21.37,1,1,418860,132660.0,0.0

In [100]:
y_train

48041    0
8697     4
41428    2
93162    4
59109    2
        ..
22606    1
48808    1
45320    4
46336    1
72612    1
Name: Rank, Length: 72498, dtype: int64

In [101]:
df.dtypes

loan_amount          int64
loan_period        float64
working_year       float64
property              int8
incomeyear           int64
DTI                float64
purpose_loan          int8
overdue_num          int64
total_repayment      int64
total_interest     float64
overdue_amount     float64
Rank                 int64
dtype: object

In [102]:
import xgboost as xgb

In [ ]:
#xgb_clf.fit(X_train,
#            y_train,
#            verbose=True,
#            early_stopping_rounds = 10,
#            eval_metric='aucpr',
#            eval_set = [(X_test,y_test)])

In [ ]:
xgb_clf = xgb.XGBClassifier(use_label_encoder=False,n_estimators=2000,objective='binary:logistic',eval_metric='logloss',missing=None,seed=42)
dmatrix = xgb.DMatrix(df, enable_categorical=True)
param_grid = dict(eta=[0.10, 0.20],
                  max_depth=[3, 8, 12],
                  min_child_weight=[1, 3],
                  gamma=[0.2, 0.4])
xgb_gscv = GridSearchCV(xgb_clf, param_grid)
xgb_gscv.fit(X_train, y_train,verbose=True)
#Area Under the Precision-Recall Curve = aucpr
#precision-recall 곡선 아래 그래프 면적